### ISSUE TITLE
diploidsquid binary?

### ISSUE THREAD

**Issue by kskuchin** [Kingsford-Group/diploidsquid#1]
hello :)

is the pre-compiled binary for diploidsquid (not the previous version, squid) available somewhere? I can't seem to find it on the page so far

**Comment by ame9yu** [comment]
Hi, I have added a pre-compiled binary for diploidsquid. You can find it over here: https://github.com/Kingsford-Group/diploidsquid/releases/tag/v1.0 

Thanks!
